using System;
using System.IO;
using System.Text;
using FluentAssertions;
using Xunit;

namespace PgpCore.Tests.UnitTests.Keys
{
    /// <summary>
    /// Regression tests for "key pair" style key files - a single armored file containing BOTH
    /// the public and the secret key material (e.g. as exported by GoAnywhere PGP Studio, or by
    /// concatenating "gpg --export" and "gpg --export-secret-keys" output). Such files contain
    /// two consecutive armor blocks and must be usable as either public or private key input
    /// (GitHub issues #316 and #311).
    /// </summary>
    public class CombinedKeyFiles : TestBase
    {
        [Theory]
        [InlineData(KeyType.Known)]
        [InlineData(KeyType.KnownGpg)]
        [InlineData(KeyType.Generated)]
        public void EncryptAndSign_WithCombinedKeyFileAsBothKeys_ShouldDecryptAndVerify(KeyType keyType)
        {
            // Arrange - a single string holding two armor blocks (public block then private block).
            TestFactory testFactory = new TestFactory();
            testFactory.Arrange(keyType, FileType.Known);
            string combinedKey = testFactory.PublicKey + "\n" + testFactory.PrivateKey;

            EncryptionKeys encryptionKeys = new EncryptionKeys(combinedKey, combinedKey, testFactory.Password);
            PGP pgp = new PGP(encryptionKeys);

            // Act
            string encryptedContent = pgp.EncryptAndSign(testFactory.Content);
            string decryptedContent = pgp.DecryptAndVerify(encryptedContent);

            // Assert
            decryptedContent.Should().Be(testFactory.Content);

            // Teardown
            testFactory.Teardown();
        }

        [Theory]
        [InlineData(KeyType.Known)]
        [InlineData(KeyType.KnownGpg)]
        [InlineData(KeyType.Generated)]
        public void Sign_WithCombinedKeyFileAsPrivateKeyOnly_ShouldVerify(KeyType keyType)
        {
            // Arrange - the combined key is used with the private-key-only constructor.
            TestFactory testFactory = new TestFactory();
            testFactory.Arrange(keyType, FileType.Known);
            string combinedKey = testFactory.PublicKey + "\n" + testFactory.PrivateKey;

            EncryptionKeys signingKeys = new EncryptionKeys(combinedKey, testFactory.Password);
            EncryptionKeys verificationKeys = new EncryptionKeys(testFactory.PublicKey);
            PGP pgpSign = new PGP(signingKeys);
            PGP pgpVerify = new PGP(verificationKeys);

            // Act
            string signedContent = pgpSign.Sign(testFactory.Content);
            bool verified = pgpVerify.Verify(signedContent);

            // Assert
            verified.Should().BeTrue();

            // Teardown
            testFactory.Teardown();
        }

        [Theory]
        [InlineData(KeyType.Known)]
        [InlineData(KeyType.KnownGpg)]
        public void Encrypt_WithPrivateKeyAsPublicKeyInput_ShouldDecrypt(KeyType keyType)
        {
            // Arrange - a private key block only, passed as public key input; the public parts
            // must be derived from the secret key ring.
            TestFactory testFactory = new TestFactory();
            testFactory.Arrange(keyType, FileType.Known);

            EncryptionKeys encryptKeys = new EncryptionKeys(testFactory.PrivateKey);
            EncryptionKeys decryptKeys = new EncryptionKeys(testFactory.PrivateKey, testFactory.Password);
            PGP pgpEncrypt = new PGP(encryptKeys);
            PGP pgpDecrypt = new PGP(decryptKeys);

            // Act
            string encryptedContent = pgpEncrypt.Encrypt(testFactory.Content);
            string decryptedContent = pgpDecrypt.Decrypt(encryptedContent);

            // Assert
            decryptedContent.Should().Be(testFactory.Content);

            // Teardown
            testFactory.Teardown();
        }

        [Fact]
        public void GenerateKey_LoadedViaEncryptionKeys_ShouldRoundTrip()
        {
            // Arrange - keys generated by PgpCore itself, loaded back through EncryptionKeys
            // (guards against "unknown object in stream SecretSubkey", issue #311).
            TestFactory testFactory = new TestFactory();
            testFactory.Arrange(KeyType.Generated, FileType.Known);

            using (Stream publicKeyStream = testFactory.PublicKeyStream)
            using (Stream privateKeyStream = testFactory.PrivateKeyStream)
            {
                EncryptionKeys encryptionKeys = new EncryptionKeys(publicKeyStream, privateKeyStream, testFactory.Password);
                PGP pgp = new PGP(encryptionKeys);

                // Act
                string encryptedContent = pgp.EncryptAndSign(testFactory.Content);
                string decryptedContent = pgp.DecryptAndVerify(encryptedContent);

                // Assert
                decryptedContent.Should().Be(testFactory.Content);
            }

            // Teardown
            testFactory.Teardown();
        }

        [Fact]
        public void ReadSecretKeyRingBundle_WithGarbageTextInput_ShouldThrowInvalidKeyMaterialException()
        {
            // Arrange
            using (Stream garbageStream = new MemoryStream(Encoding.UTF8.GetBytes("this is not a pgp key")))
            {
                // Act
                Action act = () => Utilities.ReadSecretKeyRingBundle(garbageStream);

                // Assert
                act.Should().Throw<InvalidKeyMaterialException>();
            }
        }

        [Fact]
        public void ReadSecretKeyRingBundle_WithGarbageBinaryInput_ShouldThrowInvalidKeyMaterialException()
        {
            // Arrange - first byte has the high bit set so the input is treated as binary PGP data.
            using (Stream garbageStream = new MemoryStream(new byte[] { 0xFF, 0x13, 0x37, 0x00, 0x42 }))
            {
                // Act
                Action act = () => Utilities.ReadSecretKeyRingBundle(garbageStream);

                // Assert
                act.Should().Throw<InvalidKeyMaterialException>();
            }
        }

        [Fact]
        public void ReadSecretKeyRingBundle_WithPublicKeyOnlyInput_ShouldThrowInvalidKeyMaterialException()
        {
            // Arrange - valid key material, but with no secret keys in it.
            TestFactory testFactory = new TestFactory();
            testFactory.Arrange(KeyType.Known, FileType.Known);

            using (Stream publicKeyStream = testFactory.PublicKeyStream)
            {
                // Act
                Action act = () => Utilities.ReadSecretKeyRingBundle(publicKeyStream);

                // Assert
                act.Should().Throw<InvalidKeyMaterialException>()
                    .WithMessage("No PGP secret keys found*");
            }

            // Teardown
            testFactory.Teardown();
        }
    }
}
